name: Build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build container
        run: docker build -t trumant/terraform-module-versions-action:${{ github.sha }} .
